source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.0.0'
gem 'haml-rails'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'sqlite3'
gem 'stripe_event'
gem 'uglifier', '>= 1.3.0'
gem 'bootstrap-sass', '~> 3.1.0'
